### ISSUE TITLE
Support MMap

### ISSUE THREAD

**Issue by roseduan** [rosedblabs/wal#18]

**Comment by amityahav** [comment]
Hey @roseduan i would like to contribute. can u elaborate on that?
were u thinking about mmapping the content of a segment file instead of keeping a file descriptor and do the reading by it ?

**Comment by roseduan** [comment]
Yes, we can map the file to improve read/write performance in some scenarios.
there are some helpful links:
https://github.com/akrylysov/pogreb/tree/master/fs
https://github.com/dgraph-io/ristretto/blob/main/z/mmap.go
https://github.com/edsrzf/mmap-go

**Comment by roseduan** [comment]
I can assign this issue to you if you`d like to contribute.
List a plan first and do not rush to write the code, we can discuss it.

**Comment by amityahav** [comment]
Yes I'll do that, thanks for the links. Do you want it to be an optional feature ? Meaning I can either use the file mapped or not

**Comment by roseduan** [comment]
> Yes I'll do that, thanks for the links. Do you want it to be an optional feature ? Meaning I can either use the file mapped or not

Yes, should be an option when opening the WAL.
We can refer to pogreb, a filesystem interface, with two implementations(StandardFile and MMap).

**Comment by amityahav** [comment]
my initial thoughts are to create a file interface backed by the os.File which will be implemented by 2 different structs: 
1. mmapFile struct which will contain the mapped slice, fd etc.. 
2. osFile struct which will have the fd and the LRU cache (i guess this cache isnt needed when the file is mmapped, correct me if im wrong).

the file interface will be embedded inside the segment's struct, providing all the R/W operations needed.

**Comment by amityahav** [comment]
> > Yes I'll do that, thanks for the links. Do you want it to be an optional feature ? Meaning I can either use the file mapped or not
> 
> Yes, should be an option when opening the WAL. We can refer to pogreb, a filesystem interface, with two implementations(StandardFile and MMap).

just wrote my thoughts concurrently :D

**Comment by roseduan** [comment]
> my initial thoughts are to create a file interface backed by the os.File which will be implemented by 2 different structs:
> 
> 1. mmapFile struct which will contain the mapped slice, fd etc..
> 2. osFile struct which will have the fd and the LRU cache (i guess this cache isnt needed when the file is mmapped, correct me if im wrong).
> 
> the file interface will be embedded inside the segment's struct, providing all the R/W operations needed.

yes, cache is not needed when file is mapped.
The interface name `FileSystem` will be better.

These are all my thoughts.

**Comment by amityahav** [comment]
as i understand after some reading you cant really append to the mmapped file but the next record should be written to the underlying file and then a re-map should be applied if the file size is larger than the maping that was allocated.
we could always map each segment with the size that is specified in the options (1GB as a default) but wouldnt it kill the procces's address space in case there are alot of open segments?

**Comment by roseduan** [comment]
> 

Yes, you are correct, let me rethink it, re-map every time is very costly.

**Comment by amityahav** [comment]
I know that mysqllite wal is mmapped. I'll do some more diggings in the weekend

**Comment by amityahav** [comment]
https://stackoverflow.com/questions/35891525/mmap-for-writing-sequential-log-file-for-speed
great discussion regarding appending to a file and the overhead that comes with it. also i think that even for reading purposes, mmap is good for random access where as for WAL its sequential so i guess there is no much of an improvement mmaping for reads. lemme know what u think

**Comment by amityahav** [comment]
@roseduan

**Comment by roseduan** [comment]
OK, seems that MMap is not suitable for sequential reading or writing, I think we can do it later if someone acquires it with a specific case.

Anyway, thanks for your attention.
