### ISSUE TITLE
wrong commets

### ISSUE THREAD

**Issue by SPCDTS** [rosedblabs/wal#2]
https://github.com/rosedblabs/wal/blob/5178372aa6c3cd471981cd181d9d74afa300c0a9/segment.go#L32-L34

Type and Lenght should be exchanged.

According to
https://github.com/rosedblabs/wal/blob/5178372aa6c3cd471981cd181d9d74afa300c0a9/segment.go#L224-L232

**Comment by roseduan** [comment]
Thanks.

Should be written like this:

 // Checksum Type Length 
 //           4         1        2 

PR welome.

**Comment by roseduan** [comment]
fixed in #3
