### ISSUE TITLE
optimize writeInternal

### ISSUE THREAD

**Issue by roseduan** [rosedblabs/wal#20]
If the data is greater than blockSize(32k), it will call Write multiple times, which will have cost(because of the System call), we can cache it in the buffer pool and write all once.

**Comment by amityahav** [comment]
Hey can i take this?

**Comment by roseduan** [comment]
> Hey can i take this?

OK， thanks

**Comment by amityahav** [comment]
@roseduan hey, did u have the chance to look on the PR?

**Comment by roseduan** [comment]
> @roseduan hey, did u have the chance to look on the PR?

Sorry I only maintain the project in my spare time, apologize if I have any delay.
