### ISSUE TITLE
Batch writes

### ISSUE THREAD

**Issue by amityahav** [rosedblabs/wal#23]
it would be nice to support batch writes.
i want to be able to buffer all of my DB modifications that are appended to the WAL during a batch insert and only when the batch insert is completed flush it to the underlying file.

**Comment by roseduan** [comment]
I have thought about this before, but I need more time to design how to implement it.

**Comment by amityahav** [comment]
this can also optimize batch inserts in rosedb

**Comment by roseduan** [comment]
Here is my thought:

1. Add a function named `PendingWrites(data []byte)`
   * all new data will be maintained in WAL `pendingWrites [][]byte`
2. Add a function named `WriteAll`
   * write all data in pendingWrites
   * update blockNumber and blockSize
   * reset the `pendingWrites` in wal
   * return all `ChunkPosition`

**Comment by iefnaf** [comment]
> 



> Here is my thought:
> 
> 1. Add a function named `PendingWrites(data []byte)`
>    
>    * all new data will be maintained in WAL `pendingWrites [][]byte`
> 2. Add a function named `WriteAll`
>    
>    * write all data in pendingWrites
>    * update blockNumber and blockSize
>    * reset the `pendingWrites` in wal
>    * return all `ChunkPosition`

hello，可以把这个feature分给我吗？我最近在学习WAL相关的知识，对这个挺感兴趣，不知道有没有人已经在做了。
