### ISSUE TITLE
Support Data Compression

### ISSUE THREAD

**Issue by roseduan** [rosedblabs/wal#29]
Snappy
https://github.com/golang/snappy
ZSTD
https://github.com/DataDog/zstd

**Comment by david990917** [comment]
Shall we use these api to compress the disk file? 

We could add the interface of `compress()` and `decompress` when reading

**Comment by roseduan** [comment]
> Shall we use these api to compress the disk file?
> 
> We could add the interface of `compress()` and `decompress` when reading

Compressing a whole file seems not reasonable.
