### ISSUE TITLE
Import CLOCK-Pro caching algorithm

### ISSUE THREAD

**Issue by roseduan** [rosedblabs/wal#30]
Import CLOCK-Pro caching algorithm to manage the block read and decompress.

Aims to avoid allocating new bytes every time while reading or decompressing.

**Comment by david990917** [comment]
I have some idea about how the clock-pro caching algorithm works. Could be Hot / Cold Cache

May I ask what the expectation of working with reading or decompressing is?

**Comment by roseduan** [comment]
> I have some idea about how the clock-pro caching algorithm works. Could be Hot / Cold Cache
> 
> May I ask what the expectation of working with reading or decompressing is?

It's just my initial idea, let me recheck it.
Thanks for your attention.
