### ISSUE TITLE
An unreachable if branch

### ISSUE THREAD

**Issue by iefnaf** [rosedblabs/wal#34]
https://github.com/rosedblabs/wal/blob/8de919049e2859973403f45d11920f383e43a0e8/segment.go#L225

chunkSize <= leftSize, end <= dataSize, the second if branch is unreachable.
```go
if chunkSize > leftSize {
chunkSize = leftSize
}

var end = dataSize - leftSize + chunkSize
if end > dataSize {
end = dataSize
}
```

**Comment by roseduan** [comment]
Just a corner case check to make the code more understandable.
